### PR TITLE
add cmd and common module

### PR DESCRIPTION
**Pull request by odd-man**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/dashboard-api/4)

### CODE REVIEW

**Comment by mayongxing1983** [comment]
Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---

*[cmd/api/cmd/config_test.go, line 19 at r1](https://reviewable.io/reviews/seeleteam/dashboard-api/4#-LDnykp88-cu2Pwm4VCa:-LDnykp93L6OMoJug4OI:b-3jie2g) ([raw file](https://github.com/seeleteam/dashboard-api/blob/382602fff962abcb0f2099e563817dbde18e4705/cmd/api/cmd/config_test.go#L19)):*
> ```Go
> 		fmt.Printf("app.json %v", config)
> 	}
> 	fmt.Printf("%#v", config)
> ```

Testcase must has two check point: 1. file exist, check config item  2 filt not exist check error

---

*[cmd/api/cmd/config_test.go, line 28 at r1](https://reviewable.io/reviews/seeleteam/dashboard-api/4#-LDnz5jH0G8JbRej6Evl:-LDnz5jI4bzUunz9jWdj:b-3jie2g) ([raw file](https://github.com/seeleteam/dashboard-api/blob/382602fff962abcb0f2099e563817dbde18e4705/cmd/api/cmd/config_test.go#L28)):*
> ```Go
> 		fmt.Printf("app.json %v", config)
> 	}
> 	fmt.Printf("%#v", *config)
> ```

Testcase must has two check point: 1. file exist, check config item  2 filt not exist check error

---

*[cmd/api/cmd/root.go, line 19 at r1](https://reviewable.io/reviews/seeleteam/dashboard-api/4#-LDnzkbL7fVDyzIIfph3:-LDnzkbL7fVDyzIIfph4:bcvylww) ([raw file](https://github.com/seeleteam/dashboard-api/blob/382602fff962abcb0f2099e563817dbde18e4705/cmd/api/cmd/root.go#L19)):*
> ```Go
> 	Use:   "api",
> 	Short: "api command for starting the api",
> 	Long:  `use "api help [<command>]" for detailed usage`,
> ```

command api should be dashboard-api ?

---

*[cmd/api/cmd/start.go, line 27 at r1](https://reviewable.io/reviews/seeleteam/dashboard-api/4#-LDnzwJy7RLPdFyMsNvr:-LDnzwJy7RLPdFyMsNvs:b-6p213u) ([raw file](https://github.com/seeleteam/dashboard-api/blob/382602fff962abcb0f2099e563817dbde18e4705/cmd/api/cmd/start.go#L27)):*
> ```Go
> 	Long: `usage example:
> 		api.exe start -c cmd\app.json
> 		start the api.`,
> ```

api should be dashboard-api

---

*[cmd/api/config/app.json, line 26 at r1](https://reviewable.io/reviews/seeleteam/dashboard-api/4#-LDo-Z85-nf39dOyrVjO:-LDo-Z85-nf39dOyrVjP:bk6e00w) ([raw file](https://github.com/seeleteam/dashboard-api/blob/382602fff962abcb0f2099e563817dbde18e4705/cmd/api/config/app.json#L26)):*
> ```JSON
>       "DBMaxActive":0,
>       "DBIdleTimetout":0
>     }
> ```

don't use 0 for initial config item

---

*[common/request.go, line 202 at r1](https://reviewable.io/reviews/seeleteam/dashboard-api/4#-LDo30l19sCwX7x71mW1:-LDo30l19sCwX7x71mW2:b-c9fekv) ([raw file](https://github.com/seeleteam/dashboard-api/blob/382602fff962abcb0f2099e563817dbde18e4705/common/request.go#L202)):*
> ```Go
> 	// RequestSQL the sql or sql array field in request
> 	RequestSQL = "sql"
> )
> ```

note should relate to const  variable，please simplify the note

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/dashboard-api/4)*

**Comment by odd-man** [comment]
Review status: 0 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/api/cmd/config_test.go, line 19 at r1](https://reviewable.io/reviews/seeleteam/dashboard-api/4#-LDnykp88-cu2Pwm4VCa:-LDoDxIx7MyEI7EehR0r:b-7ql1td) ([raw file](https://github.com/seeleteam/dashboard-api/blob/382602fff962abcb0f2099e563817dbde18e4705/cmd/api/cmd/config_test.go#L19)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

Testcase must has two check point: 1. file exist, check config item  2 filt not exist check error
</blockquote></details>

fixed

---

*[cmd/api/cmd/config_test.go, line 28 at r1](https://reviewable.io/reviews/seeleteam/dashboard-api/4#-LDnz5jH0G8JbRej6Evl:-LDoE-1kCYb7J4RPoejg:b-7ql1td) ([raw file](https://github.com/seeleteam/dashboard-api/blob/382602fff962abcb0f2099e563817dbde18e4705/cmd/api/cmd/config_test.go#L28)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

Testcase must has two check point: 1. file exist, check config item  2 filt not exist check error
</blockquote></details>

fixed

---

*[cmd/api/cmd/root.go, line 19 at r1](https://reviewable.io/reviews/seeleteam/dashboard-api/4#-LDnzkbL7fVDyzIIfph3:-LDoE3p6-xYTNKGFiHpQ:b-7ql1td) ([raw file](https://github.com/seeleteam/dashboard-api/blob/382602fff962abcb0f2099e563817dbde18e4705/cmd/api/cmd/root.go#L19)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

command api should be dashboard-api ?
</blockquote></details>

fixed

---

*[cmd/api/cmd/start.go, line 27 at r1](https://reviewable.io/reviews/seeleteam/dashboard-api/4#-LDnzwJy7RLPdFyMsNvr:-LDoE6CsEHafCdVh7oAQ:b-7ql1td) ([raw file](https://github.com/seeleteam/dashboard-api/blob/382602fff962abcb0f2099e563817dbde18e4705/cmd/api/cmd/start.go#L27)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

api should be dashboard-api
</blockquote></details>

fixed

---

*[cmd/api/config/app.json, line 26 at r1](https://reviewable.io/reviews/seeleteam/dashboard-api/4#-LDo-Z85-nf39dOyrVjO:-LDoE9mI4A6NZHu9EdN_:b-7ql1td) ([raw file](https://github.com/seeleteam/dashboard-api/blob/382602fff962abcb0f2099e563817dbde18e4705/cmd/api/config/app.json#L26)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

don't use 0 for initial config item
</blockquote></details>

fixed

---

*[common/request.go, line 202 at r1](https://reviewable.io/reviews/seeleteam/dashboard-api/4#-LDo30l19sCwX7x71mW1:-LDoEDMRDBgvdhglbTZd:b-7ql1td) ([raw file](https://github.com/seeleteam/dashboard-api/blob/382602fff962abcb0f2099e563817dbde18e4705/common/request.go#L202)):*
<details><summary><i>Previously, mayongxing1983 (luckystart Ma) wrote…</i></summary><blockquote>

note should relate to const  variable，please simplify the note
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/dashboard-api/4)*

**Comment by webbergao1** [comment]
Review status: 3 of 12 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/dashboard-api/4)*

**Comment by mayongxing1983** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/seeleteam/dashboard-api/4)*

**Pull request merged**
